using System.Text;
using System.Text.Json;
using LogitechLuaRecorder.App.Models;

namespace LogitechLuaRecorder.App.Services;

public sealed class LuaScriptSerializer
{
    private const string MetadataStartMarker = "-- LogitechLuaRecorder.Metadata.Start";
    private const string MetadataEndMarker = "-- LogitechLuaRecorder.Metadata.End";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = false,
    };

    public string Serialize(MacroDocumentData document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var metadataJson = JsonSerializer.Serialize(document, JsonOptions);
        var metadataBase64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(metadataJson));

        var builder = new StringBuilder();
        builder.AppendLine(MetadataStartMarker);
        builder.AppendLine($"-- {metadataBase64}");
        builder.AppendLine(MetadataEndMarker);
        builder.AppendLine("-- Generated by Logitech Lua Recorder.");
        builder.AppendLine("-- Adjust TRIGGER_GKEY if you want to bind playback to a different G-key.");
        builder.AppendLine();
        builder.AppendLine($"local TRIGGER_GKEY = {Math.Max(1, document.TriggerGKey)}");
        builder.AppendLine($"local VIRTUAL_LEFT = {document.CaptureBounds.Left}");
        builder.AppendLine($"local VIRTUAL_TOP = {document.CaptureBounds.Top}");
        builder.AppendLine($"local VIRTUAL_WIDTH = {Math.Max(1, document.CaptureBounds.Width)}");
        builder.AppendLine($"local VIRTUAL_HEIGHT = {Math.Max(1, document.CaptureBounds.Height)}");
        builder.AppendLine();
        builder.AppendLine("local function clamp(value, min_value, max_value)");
        builder.AppendLine("    if value < min_value then return min_value end");
        builder.AppendLine("    if value > max_value then return max_value end");
        builder.AppendLine("    return value");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function move_mouse_pixel(x, y)");
        builder.AppendLine("    local normalized_x = math.floor(((x - VIRTUAL_LEFT) / math.max(1, VIRTUAL_WIDTH - 1)) * 65535)");
        builder.AppendLine("    local normalized_y = math.floor(((y - VIRTUAL_TOP) / math.max(1, VIRTUAL_HEIGHT - 1)) * 65535)");
        builder.AppendLine("    MoveMouseTo(clamp(normalized_x, 0, 65535), clamp(normalized_y, 0, 65535))");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function play_recording()");

        foreach (var record in document.Events)
        {
            AppendEvent(builder, record);
        }

        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("function OnEvent(event, arg, family)");
        builder.AppendLine("    if event == \"PROFILE_ACTIVATED\" then");
        builder.AppendLine("        EnablePrimaryMouseButtonEvents(true)");
        builder.AppendLine("    elseif event == \"G_PRESSED\" and arg == TRIGGER_GKEY then");
        builder.AppendLine("        play_recording()");
        builder.AppendLine("    end");
        builder.AppendLine("end");

        return builder.ToString();
    }

    public MacroDocumentData Deserialize(string text)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(text);

        var startIndex = text.IndexOf(MetadataStartMarker, StringComparison.Ordinal);
        var endIndex = text.IndexOf(MetadataEndMarker, StringComparison.Ordinal);
        if (startIndex < 0 || endIndex <= startIndex)
        {
            throw new InvalidOperationException("This Lua file does not contain recorder metadata. Only files generated by this app can be reopened.");
        }

        var metadataSegmentStart = startIndex + MetadataStartMarker.Length;
        var metadataSegment = text[metadataSegmentStart..endIndex];
        var metadataLine = metadataSegment
            .Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .FirstOrDefault(line => line.StartsWith("-- ", StringComparison.Ordinal));

        if (metadataLine is null)
        {
            throw new InvalidOperationException("Recorder metadata block is present but empty.");
        }

        var metadataBase64 = metadataLine[3..].Trim();
        try
        {
            var metadataJson = Encoding.UTF8.GetString(Convert.FromBase64String(metadataBase64));
            var document = JsonSerializer.Deserialize<MacroDocumentData>(metadataJson, JsonOptions);
            return document ?? throw new InvalidOperationException("Recorder metadata was empty.");
        }
        catch (Exception exception) when (exception is FormatException or JsonException)
        {
            throw new InvalidOperationException("Recorder metadata could not be decoded.", exception);
        }
    }

    private static void AppendEvent(StringBuilder builder, MacroEventRecord record)
    {
        if (record.DelayBeforeMs > 0)
        {
            builder.AppendLine($"    Sleep({record.DelayBeforeMs})");
        }

        switch (record)
        {
            case KeyMacroEventRecord keyRecord:
                AppendKeyEvent(builder, keyRecord);
                break;
            case MouseButtonMacroEventRecord mouseButtonRecord:
                builder.AppendLine($"    move_mouse_pixel({mouseButtonRecord.X}, {mouseButtonRecord.Y})");
                builder.AppendLine($"    {(mouseButtonRecord.IsButtonDown ? "PressMouseButton" : "ReleaseMouseButton")}({(int)mouseButtonRecord.Button})");
                break;
            case MouseWheelMacroEventRecord mouseWheelRecord:
                builder.AppendLine($"    move_mouse_pixel({mouseWheelRecord.X}, {mouseWheelRecord.Y})");
                builder.AppendLine($"    MoveMouseWheel({NormalizeWheelDelta(mouseWheelRecord.Delta)})");
                break;
            default:
                throw new InvalidOperationException($"Unsupported macro event record '{record.GetType().Name}'.");
        }
    }

    private static void AppendKeyEvent(StringBuilder builder, KeyMacroEventRecord record)
    {
        var functionName = record.IsKeyDown ? "PressKey" : "ReleaseKey";
        if (record.KeyScanCode is int keyScanCode)
        {
            builder.AppendLine($"    {functionName}({keyScanCode})");
            return;
        }

        if (string.IsNullOrWhiteSpace(record.KeyIdentifier))
        {
            throw new InvalidOperationException("Key events must have a key identifier or scancode.");
        }

        builder.AppendLine($"    {functionName}(\"{record.KeyIdentifier}\")");
    }

    private static int NormalizeWheelDelta(int wheelDelta)
    {
        if (wheelDelta == 0)
        {
            return 0;
        }

        var steps = wheelDelta / 120;
        if (steps != 0)
        {
            return steps;
        }

        return wheelDelta > 0 ? 1 : -1;
    }
}
